### ISSUE TITLE
Wrong codeTagEndPattern <Pre><Code> in regex?

### ISSUE THREAD

**Issue by rahul-iyer** [sotorrent/posthistory-extractor#40]
https://github.com/sotorrent/posthistory-extractor/blob/073adee72328d0cdee6b7360277a9f973e1b5182/src/org/sotorrent/posthistoryextractor/history/PostHistory.java#L103

Since its \<pre>\<code> ideal end tag should be \</code>\</pre>

**Comment by sbaltes** [comment]
Could you please clarify your question?
Keep in mind that this is a heuristic that is designed to deal with malformed content. In case you observed a post for which this approach fails in correctly extracting the post blocks, please mention the post here.

**Comment by sbaltes** [comment]
I fixed the order of the tags.
Since both the closing `pre` and the closing `code` tags were removed if the pattern matched (which it did as long as the closing `pre` pattern was present), this likely didn't case any major problems:

https://github.com/sotorrent/posthistory-extractor/blob/2625bf9eb0f047440001964f239959adc7dde256/src/org/sotorrent/posthistoryextractor/history/PostHistory.java#L327

However, if you are aware of a post with a broken code block extraction due to this bug, please let me know.

Thanks for reporting this!

**Comment by rahul-iyer** [comment]
Well, I'm just experimenting for now and noticed this doesn't work for the following case
`<row Id="12" PostTypeId="2" ParentId="11" CreationDate="2008-07-31T23:56:41.303" Score="323" Body="&lt;p&gt;Here's how I do it&lt;/p&gt;&#xA;&#xA;&lt;pre class=&quot;lang-csharp prettyprint-override&quot;&gt;&lt;code&gt;var ts = new TimeSpan(DateTime.UtcNow.Ticks - dt.Ticks);&#xA;double delta = Math.Abs(ts.TotalSeconds);&#xA;&#xA;if (delta &amp;lt; 60)&#xA;{&#xA;  return ts.Seconds == 1 ? &quot;one second ago&quot; : ts.Seconds + &quot; seconds ago&quot;;&#xA;}&#xA;if (delta &amp;lt; 120)&#xA;{&#xA;  return &quot;a minute ago&quot;;&#xA;}&#xA;if (delta &amp;lt; 2700) // 45 * 60&#xA;{&#xA;  return ts.Minutes + &quot; minutes ago&quot;;&#xA;}&#xA;if (delta &amp;lt; 5400) // 90 * 60&#xA;{&#xA;  return &quot;an hour ago&quot;;&#xA;}&#xA;if (delta &amp;lt; 86400) // 24 * 60 * 60&#xA;{&#xA;  return ts.Hours + &quot; hours ago&quot;;&#xA;}&#xA;if (delta &amp;lt; 172800) // 48 * 60 * 60&#xA;{&#xA;  return &quot;yesterday&quot;;&#xA;}&#xA;if (delta &amp;lt; 2592000) // 30 * 24 * 60 * 60&#xA;{&#xA;  return ts.Days + &quot; days ago&quot;;&#xA;}&#xA;if (delta &amp;lt; 31104000) // 12 * 30 * 24 * 60 * 60&#xA;{&#xA;  int months = Convert.ToInt32(Math.Floor((double)ts.Days / 30));&#xA;  return months &amp;lt;= 1 ? &quot;one month ago&quot; : months + &quot; months ago&quot;;&#xA;}&#xA;int years = Convert.ToInt32(Math.Floor((double)ts.Days / 365));&#xA;return years &amp;lt;= 1 ? &quot;one year ago&quot; : years + &quot; years ago&quot;;&#xA;&lt;/code&gt;&lt;/pre&gt;&#xA;&#xA;&lt;p&gt;Suggestions? Comments? Ways to improve this algorithm?&lt;/p&gt;&#xA;" OwnerUserId="1" LastEditorUserId="1271898" LastEditorDisplayName="GateKiller" LastEditDate="2018-01-12T16:10:22.637" LastActivityDate="2018-01-12T16:10:22.637" CommentCount="11" CommunityOwnedDate="2009-09-04T13:15:59.820" />`

**Comment by sbaltes** [comment]
The content you quoted above is from table `Posts` (HTML), but this extractor operates on table `PostHistory` (Markdown). `<pre class="lang-csharp prettyprint-override">` is not present in the corresponding Markdown source. However, I found another post containing a `<pre>` tag with an attribute and created a corresponding test case (see most recent commit).
